### PR TITLE
Fixes carthage build

### PR DESCRIPTION
**Pull request by TheAdamBorek**
I've made the `BentoKit` scheme not-shared so we don't longer need `ReactiveCocoa` in `Cartfile` (as @mluisbrown suggested).
It should solve https://github.com/Babylonpartners/Bento/issues/163 

It's a hotfix only. We should remove BentoKit completely from the repo in a future release.

The `hotfix/0.4.1` branch has been created form `master`.

EDIT:
I also had to update CircleCi config

### CODE REVIEW

**Comment by mluisbrown** [comment]
Is the plan to move `BentoKit` to a separate repo?

**Comment by TheAdamBorek** [comment]
I think "yes". However, the fact you asked the question I'm not sure now 😅

**Comment by mluisbrown** [comment]
Does CI only work with shared schemes? It’s a pity we have to lose CI for BentoKit with this fix for Carthage :/

**Comment by TheAdamBorek** [comment]
yeah, you are right @mluisbrown. I was saying to myself "I can delete it because we delete the BentoKit".... but we still use it internally :/ 

In that case I don't know if we should do this. I don't know CircleCI so much, however it has reported that test has failed for BentoKit in this PR.

```
#!/bin/bash -eo pipefail
script/test iphonesimulator "platform=iOS Simulator,name=iPhone 6,OS=12.2" BentoKit
^D^Dxcodebuild: error: The workspace named "Bento" does not contain a scheme named "BentoKit". The "-list" option can be used to find the names of the schemes in the workspace.
Exited with code 65
```

Maybe we should just set `ReactiveCocoa` to version `10.0.0` instead of `9.0.0` until we move BentoKit into a new repository 🤔. However, `ReactiveCocoa 10.0.0` removed `Result` dependency in favour to use Swift's Result. I have a bad feeling it's not backward compatible change :/

**Comment by mluisbrown** [comment]
Having thought about this some more, my view is that we should not make this change at all. The issue was conflicting versions of RAC. The user had `10.0.0` in their `Cartfile`, whereas `BentoKit` was requresing `9.0.0`. 

I think the correct "resolution" to the issue would have been to inform the user that, for the time being at least, if you use Bento, you have to use RAC 9.0.0.

If we keep BentoKit in this repo, then this will be, IMO, a minor issue for some users. You will just have to always use the same version of RAC that BentoKit requires 🤷‍♂ 

If we move BentoKit to a separate repo, that would solve the problem entirely.

**Review by mluisbrown — CHANGES_REQUESTED** [review]
Requesting changes so this doesn't get accidentally merged. See my comment.

**Pull request closed without merging**
